version: "3.6"

services:
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment: 
      - "POSTGRES_PASSWORD=postgres"
  # s3:
  #   image: minio/minio
  #   ports: 
  #     - "9000:9000"
  #   environment: 
  #     MINIO_ACCESS_KEY: minio
  #     MINIO_SECRET_KEY: minio111
  #   volumes:
  #     - .s3_data:/data
  #   command: server /data
